In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import neighbors,metrics

In [3]:
df=pd.read_csv('/content/car.data')

In [4]:
print(df.head(5))

  buying  maint doors persons lug_boot saftey  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [5]:
x=df[['buying','maint','saftey']]
y=df[['class']]

In [6]:
label={
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}
y['class']=y['class'].map(label)

/tmp/ipython-input-147704786.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class']=y['class'].map(label)


In [7]:
label1={
    'buying':{'vhigh':3, 'high':2,'med':1,'low':1},
    'maint':{'vhigh':3,'high':2,'med':1,'low':1},
    'saftey':{'high':3,'med':2,'low':1}
}

In [8]:
x=x.replace(label1).astype(int)
X=np.array(x)

/tmp/ipython-input-2290357154.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x=x.replace(label1).astype(int)


In [9]:
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 3]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 3]]


In [10]:
print(y)

      class
0         0
1         0
2         0
3         0
4         0
...     ...
1723      2
1724      3
1725      0
1726      2
1727      3

[1728 rows x 1 columns]


In [11]:
Y=np.array(y)

In [12]:
print(Y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]



# creating model

In [13]:
knn=neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')

In [14]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)
knn.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=25)

In [15]:
prediction=knn.predict(x_test)

In [16]:
print("prediction:",prediction)

prediction: [1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0
 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 1 1 0 0 0 0 1 0 1 0 1
 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 1 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1
 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0
 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0
 0 0 1 1 1 1 0 0 0 0 1 0 0]


In [17]:
accuracy=metrics.accuracy_score(y_test,prediction)

In [18]:
print(accuracy)

0.7485549132947977


In [19]:
print("actual value:",Y[200])
print("predicted value",knn.predict(X)[200])

actual value: [0]
predicted value 0
