In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5],dtype=float)
y=np.array([3,5,7,9,11])

In [8]:
x=x.reshape(-1,1)
y=y.reshape(-1,1)
m=x.shape[0]

In [9]:
print(x)
print(y)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [10]:
w=0.0
b=0.0

In [11]:
def predict(x,w,b):
  return x*w+b

In [13]:
print(predict(x,w,b))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [12]:
def compute_cost(x,y,w,b):
  y_pred=predict(x,w,b)
  cost=(1/m)*np.sum((y_pred-y)**2)
  return cost

In [14]:
print(compute_cost(x,y,w,b))

57.0


compute gradients

In [16]:
def compute_gradients(x,y,w,b):
  y_pred=predict(x,w,b)
  dw=(2/m)*np.sum((y_pred-y)*x)
  db=(2/m)*np.sum(y_pred-y)
  return dw,db

In [17]:
print(compute_gradients(x,y,w,b))

(np.float64(-50.0), np.float64(-14.0))


In [19]:
learning_rate=0.01
epochs=1000
for i in range(epochs):
  dw,db=compute_gradients(x,y,w,b)
  w=w-learning_rate*dw
  b=b-learning_rate*db
  if i%100==0:
    cost=compute_cost(x,y,w,b)
    print(f"epoch{i}:cost={cost:.4f}")

epoch0:cost=19.3773
epoch100:cost=0.0157
epoch200:cost=0.0080
epoch300:cost=0.0040
epoch400:cost=0.0021
epoch500:cost=0.0010
epoch600:cost=0.0005
epoch700:cost=0.0003
epoch800:cost=0.0001
epoch900:cost=0.0001


In [20]:
print("learning rate:",w)
print("learning bias:",b)

learning rate: 2.0038674622404455
learning bias: 0.9860372341728676


#more predictions

In [21]:
x_test=np.array([6,7,8]).reshape(-1,1)
y_pred=predict(x_test,w,b)
print("predictions:",y_pred.flatten())

predictions: [13.00924201 15.01310947 17.01697693]


#take a matrix perform det inverse covariance using linear regression